1

diff --git a/.github/workflows/x86_64.yml b/.github/workflows/x86_64.yml
--- a/.github/workflows/x86_64.yml
+++ b/.github/workflows/x86_64.yml
@@ -8,33 +8,47 @@
 
 name: AutoBuild-x86_64
 
+### 以下内容请保持不变
 on:
   repository_dispatch:
   workflow_dispatch:
     inputs:
       ssh:
-        description: 'SSH connection to Actions'
+        description: 'SSH 连接到 Actions'
         required: true
         default: 'false'
+      ip_addr:
+        description: '固件 IP 地址 [可选]'
+        default: ''
+### END
 
-#  schedule:
-#    - cron: 0 11 * * *
+  #push:
+  #  branches: 
+  #    - master
+
+  #schedule:
+  #  - cron: 0 8 * * 5
 
   watch:
     types: [started]
 
+### 环境变量设置
 env:
-  REPO_URL: https://github.com/coolsnowwolf/lede
-  REPO_BRANCH: master
-  CONFIG_FILE: x86_64
-  DIY_SCRIPT: Scripts/AutoBuild_DiyScript.sh
-  FUNCTION_SCRIPT: Scripts/AutoBuild_Function.sh
-  UPLOAD_RELEASE: true
-  UPLOAD_FIRMWARE: false
-  UPLOAD_BIN_DIR: false
-  REMOVE_USELESS_FILES: true
-  REMOVE_OLD_RELEASE: false
-  REMOVE_WORKFLOW_RUNS: true
+# 设备名称
+  DEFAULT_TARGET: x86_64
+# 源码仓库:分支
+  DEFAULT_SOURCE: coolsnowwolf/lede:master
+# 上传固件到 Github Releases
+  UPLOAD_RELEASES: true
+# 上传固件到 Github Artifacts
+  UPLOAD_ARTIFACTS: false
+# 上传 bin 文件夹到 Github Artifacts
+  UPLOAD_BIN_ARTIFACTS: false
+# 删除无用文件以释放更多空间
+  DELETE_USELESS_FILES: true
+# 删除早期的 workflow 任务
+  DELETE_OLD_WORKFLOW: true
+### END
 
 jobs:
   build:
@@ -44,113 +58,118 @@ jobs:
     - name: Checkout
       uses: actions/checkout@main
 
+    - name: Initialization Define Info
+      run: |
+        DEFAULT_TARGET=${{ env.DEFAULT_TARGET }}
+        DEFAULT_SOURCE=${{ env.DEFAULT_SOURCE }}
+        DELETE_USELESS_FILES=${{ env.DELETE_USELESS_FILES }}
+        echo "DEFAULT_TARGET=$DEFAULT_TARGET" >> $GITHUB_ENV
+        echo "DELETE_USELESS_FILES=$DELETE_USELESS_FILES" >> $GITHUB_ENV
+        [ ! -f "$GITHUB_WORKSPACE/Configs/$DEFAULT_TARGET" ] && {
+            echo "[ERROR] No target_config file: [$DEFAULT_TARGET] detected!"
+            exit 1
+        }
+        export REPO_URL="https://github.com/$(echo $DEFAULT_SOURCE | cut -d \: -f 1)"
+        export REPO_BRANCH=$(echo $DEFAULT_SOURCE | cut -d \: -f 2)
+        [ -z $REPO_BRANCH ] && REPO_BRANCH=master
+        echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
+        echo "REPO_BRANCH=$REPO_BRANCH" >> $GITHUB_ENV
+        echo -e "TARGET_PROFILE: $DEFAULT_TARGET\nSOURCE: $REPO_URL:$REPO_BRANCH"
+
     - name: Initialization Environment
       env:
         DEBIAN_FRONTEND: noninteractive
       run: |
         sudo -E apt-get update
-        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
+        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync qemu-utils
         sudo timedatectl set-timezone "Asia/Shanghai"
         sudo mkdir -p /workdir
         sudo chown $USER:$GROUPS /workdir
+        if [ "$DELETE_USELESS_FILES" == true ];then
+            echo "Deleting useless files,please wait ..."
+            docker rmi $(docker images -q)
+            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php
+            sudo -E apt-get -y autoremove --purge
+            sudo -E apt-get clean
+        fi
         echo "Compile_Date=$(date +%Y%m%d%H%M)" > $GITHUB_WORKSPACE/Openwrt.info
         echo "Display_Date=$(date +%Y/%m/%d)" >> $GITHUB_WORKSPACE/Openwrt.info
-        echo "Artifacts_Date=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
-        touch update_log.txt
-
-    - name: Remove useless files
-      if: env.REMOVE_USELESS_FILES == 'true' && !cancelled()
-      run: |
-        echo "Deleting useless files, please wait ..."
-        docker rmi `docker images -q`
-        sudo rm -rf \
-          /usr/share/dotnet \
-          /etc/mysql \
-          /etc/php
-        sudo -E apt-get -y autoremove --purge
-        sudo -E apt-get clean
+        echo "Defined_IP_Address=${{ github.event.inputs.IP }}" >> $GITHUB_WORKSPACE/Openwrt.info
+        echo "Openwrt_Repo=$REPO_URL" >> $GITHUB_WORKSPACE/Openwrt.info
+        echo "Artifacts_Date=$(date +%m%d%H%M)" >> $GITHUB_ENV
+        touch Release_info
       
-    - name: Clone source code
+    - name: Clone Openwrt Source Code
       run: |
         git clone -b $REPO_BRANCH $REPO_URL openwrt
         ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
-        [ -f Configs/$CONFIG_FILE ] && cp Configs/$CONFIG_FILE openwrt/.config || {
-            echo "未检测到该设备的 $CONFIG_FILE 配置文件!"
-            exit 1
-        }
         cd openwrt
         ./scripts/feeds update -a
-        ./scripts/feeds install -a
-        make defconfig
+        ./scripts/feeds install -a > /dev/null 2>&1
 
-    - name: Run Custom Firmware-Diy Scripts
+    - name: Run AutoBuild_DiyScript.sh
       run: |
-        chmod +x $DIY_SCRIPT
-        chmod +x $FUNCTION_SCRIPT
+        chmod +x Scripts/AutoBuild_*.sh
+        cp $GITHUB_WORKSPACE/Configs/$DEFAULT_TARGET openwrt/.config
         cd openwrt
-        source $GITHUB_WORKSPACE/$DIY_SCRIPT
-        source $GITHUB_WORKSPACE/$FUNCTION_SCRIPT && Firmware-Diy_Base
-        Firmware-Diy
+        make defconfig > /dev/null 2>&1
+        source $GITHUB_WORKSPACE/Scripts/AutoBuild_DiyScript.sh
+        source $GITHUB_WORKSPACE/Scripts/AutoBuild_Function.sh
+        Firmware-Diy_Base && Firmware-Diy
+        rm -f .config && cp $GITHUB_WORKSPACE/Configs/$DEFAULT_TARGET .config
 
-    - name: SSH connection to Actions
+    - name: SSH Connection to Actions
       uses: P3TERX/ssh2actions@v1.0.0
-      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
+      if: (github.event.inputs.SSH == 'true' && github.event.inputs.SSH  != 'false') || contains(github.event.action, 'SSH')
       env:
         TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
         TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
 
-    - name: Preload and Compile the Openwrt
+    - name: Compile
       run: |
-        cp Configs/$CONFIG_FILE openwrt/.config
+        export Compile_Result=false
         cd openwrt
-        ./scripts/feeds install -a
+        source $GITHUB_WORKSPACE/Scripts/AutoBuild_Function.sh && Other_Scripts
+        rm -rf ./tmp && ./scripts/feeds install -a > /dev/null 2>&1
         make defconfig
         make download -j$(nproc)
-        echo "Start to compile OpenWrt ..."
         make -j$(nproc) || make -j1 V=s
+        [ $? == 0 ] && Compile_Result=true
+        echo "Compile_Result=$Compile_Result" >> $GITHUB_ENV
 
-    - name: Process the AutoBuild Firmware
+    - name: Process Firmware
+      if: env.Compile_Result == 'true' && !cancelled()
       run: |
         cd openwrt
-        source $GITHUB_WORKSPACE/$DIY_SCRIPT
-        source $GITHUB_WORKSPACE/$FUNCTION_SCRIPT && PS_Firmware
+        source $GITHUB_WORKSPACE/Scripts/AutoBuild_Function.sh && PS_Firmware
 
     - name: Upload Firmware to Artifacts
       uses: actions/upload-artifact@main
-      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
+      if: env.UPLOAD_ARTIFACTS == 'true' && env.Compile_Result == 'true' && !cancelled()
       with:
-        name: OpenWrt_Firmware_${{ env.Artifacts_DATE }}
+        name: ${{ env.DEFAULT_TARGET }}_${{ env.REPO_BRANCH }}_firmware_${{ env.Artifacts_Date }}
         path: openwrt/bin/Firmware
-        
-    - name: Upload bin directory to Artifacts
+
+    - name: Upload bin to Artifacts
       uses: actions/upload-artifact@main
-      if: env.UPLOAD_BIN_DIR == 'true' && !cancelled()
+      if: env.UPLOAD_BIN_ARTIFACTS == 'true' && env.Compile_Result == 'true' && !cancelled()
       with:
-        name: OpenWrt_bin_${{ env.Artifacts_DATE }}
+        name: ${{ env.DEFAULT_TARGET }}_${{ env.REPO_BRANCH }}_bin_${{ env.Artifacts_Date }}
         path: openwrt/bin
 
-    - name: Upload Firmware to Release
+    - name: Upload Firmware to Github Releases
       uses: softprops/action-gh-release@v1
-      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
+      if: env.UPLOAD_RELEASES == 'true' && env.Compile_Result == 'true' && !cancelled()
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         tag_name: AutoUpdate
-        body_path: update_log.txt
+        body_path: Release_info
         files: openwrt/bin/Firmware/*
-        
-    - name: Remove old Release
-      uses: dev-drprasad/delete-older-releases@v0.1.0
-      if: env.REMOVE_OLD_RELEASE == 'true' && !cancelled()
-      with:
-        keep_latest: 3
-        delete_tags: true
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        
-    - name: Remove workflow runs
+
+    - name: Delete old Workflow Runs
       uses: GitRML/delete-workflow-runs@main
-      if: env.REMOVE_WORKFLOW_RUNS == 'true' && !cancelled()
+      if: env.DELETE_OLD_WORKFLOW == 'true' && !cancelled()
       with:
         retain_days: 1
         keep_minimum_runs: 3
